version: "3"

networks:
  hakka:
    driver: bridge

volumes:
  hakka-cache:

services:
  hakka-client:
    image: jsdc2021/hakka-client-next:b0.20240919.159
    container_name: hakka-client
    ports:
      - 11700:3000
    networks:
      - hakka
